name: unit-tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  unit-tests:
    runs-on: docker://ekohandel/chisel:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run unit tests
        shell: bash
        working-directory: ./ch1-ex
        run: sbt test
